FROM node:18-bullseye-slim as builder

ARG NODE_ENV=production
ARG ENV=production

RUN apt-get update
RUN apt-get install -y build-essential unzip nasm libtool make bash git autoconf wget zlib1g-dev python3

WORKDIR /src

COPY / ./
RUN npm install --include=dev

WORKDIR /src/backend
RUN npx tsc --removeComments true

WORKDIR /src/ui.admin-mui
RUN npx next build && npx next export

FROM nginx:alpine
COPY --from=builder  /src/ui.admin-mui/out /app/static
COPY ./ui.admin-mui/nginx.conf /etc/nginx/nginx.conf